### PR TITLE
Another patch for fluxgui: End of the year/New Year special

### PR DESCRIPTION
**Pull request by aaferrari**
This time I have been working on `fluxgui-1.1.8-pid-collision.patch` patch a few weeks to solve a very "peculiar" bug.
It turns out that some time ago I noticed that fluxgui not always initiated. When checking I discovered that on those occasions appeared the following:
```
fluxgui is already running, exiting
Exception AttributeError: AttributeError("'FluxGUI' object has no attribute 'xflux_controller'",) in <bound method FluxGUI.__del__ of <__main__.FluxGUI object at 0xb5965ccc>> ignored
```
The strangest thing is that before this does not happen so at first I thought that the program was reusing the PID of previous session¹ (perhaps due to an update of [OpenRC](https://packages.gentoo.org/packages/sys-apps/openrc) and/or the kernel) but reviewing the code and making several test I discovered that the responsible was the function `os.kill()`, which not only checks the pid of the process, also the threads pids², this is a real example in one of the times that the program does not started:
```
$ cat ~/.fluxgui.pid³
2586
$ ps -eLf | grep 2586
usuario   2578  2473  2586  0    5 nov30 tty1     00:00:00 zeitgeist-datahub
```
Finally I changed the `try` by a `if` that run the `ps` command to see if there is another process with that pid and if it belongs to Python.⁴ Since then the program runs normally but anyway I would like you try it with the patch applied to check that fluxgui works correctly.
To finish and seeing [the number of bugs that I have been correcting throughout 2015](https://github.com/and3k/and3k-sunrise/pulls?q=is%3Apr+is%3Aclosed), I think send a pull request to Kilian with the last three patches⁵ (including this one), so it is possible that eventually you find yourself with an update of fluxgui in [his repository](https://github.com/Kilian/f.lux-indicator-applet).

PS: I know I did the commit before Christmas, but so far had not had enough time to write/translate all this and send it so I decided to take advantage today rather than keep postponing it `;-)`.

----
1: If you ask for the check `if pid == oldpid: ...`, I added for that.
2: If you are interested to know more about it, [here](http://stackoverflow.com/questions/1826824/os-kill-not-raising-an-oserror-however-i-do-not-see-the-given-pid-running) explain better.
3: Always I have open the program and when leave the graphical environment seems that the desktop sends a [SIGKILL](https://en.wikipedia.org/wiki/Unix_signal#SIGKILL) to all processes (do not know if it only happens in XFCE or if it is something common in all desktop environments).
4: Perhaps this last seems redundant but you would not believe how many times I've found that `oldpid` directly coincides with the pid of a different process.
5: I do not include the [AppIndicator patch](https://github.com/and3k/and3k-sunrise/blob/master/app-misc/fluxgui/files/fluxgui-1.1.8-appindicator.patch) because seems to be a problem exclusive of Gentoo.

### CODE REVIEW

**Comment by and3k** [comment]
Thanks! Excellent work! :)
